name: HLSLInterpreter CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Install dependencies
      run: dotnet restore HLSLInterpreter/HLSLInterpreter.sln
    - name: Build
      run: dotnet build HLSLInterpreter/HLSLInterpreter.sln
    - name: Test
      run: dotnet test HLSLInterpreter.Tests/HLSLInterpreter.Tests.csproj
